[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "surimi"
dynamic = ["version"]
description = "Simple test library fully written in python"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name = "Nicolas Beuve", email = "nicolas@beuve.net"}]
dependencies = ["click", "rich"]

[project.scripts]
surimi = "surimi.cli:test"

[tool.setuptools.package-data]
surimi = ["./docs/surimi.svg"]

[tool.setuptools]
packages = ["surimi", "surimi.decorators"]
package-dir = {"surimi" = "lib"}
